# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
daysUntilClose: 7

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: []

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels: []

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

issues:
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
  # Comment to post when closing a stale issue.
  closeComment: >
    Closing this issue after a prolonged period of inactivity. Please create a new issue with up-to-date information if needed. Thank you.
  # Label to use when marking as stale
  staleLabel: 'stale(issue): inactive'

pulls:
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
  # Comment to post when closing a stale pull request.
  closeComment: >
    Closing this pull request after a prolonged period of inactivity. Please ask for this pull request to be reopened if needed. Thank you.
  # Label to use when marking as stale
  staleLabel: 'stale(pull): inactive'
